### PR TITLE
Fix Translations and Add batch uninstalling

### PR DESCRIPTION
**Pull request by Akianonymus**
All credits to Lonami for batch Uninstall
Just created this pr as Lonami is not fixing the conflict

### CODE REVIEW

**Review by nikwen — CHANGES_REQUESTED** [review]
Thank you for resolving the merge conflicts of @Lonami's PR.

However, I think that the changelog is way too big. If you want your contributions to be reviewed by a project's maintainer, submit them as separate PRs, each with a changelog as short as possible.
Each PR should only add a single feature or fix a single bug. So submit one PR for the batch uninstall feature, a different one for your changes to the English strings, a different one for the .gitignore, another one for the build.sh, etc. That makes things a lot easier for reviewers.

Apart from that, this has other existing PRs merged in that should be reviewed separately (and that merge without any conflicts).

For all other things, see my inline comments.

**Comment by Lonami** [comment]
> as Lonami is not fixing the conflict

Heh thanks I was unaware the repository got new commits :)

**Comment by jensstein** [comment]
i agree with @nikwen's comments.
and besides that, i'm not really sure i want oab to do batch uninstalls. i'm not even sure if i want it to do uninstalls in the first place. i think this functionality should be separated out into some other app manager.

**Comment by Lonami** [comment]
@jensstein if you are able to backup and *install* a backup, I can't see why the inverse (uninstalling) shouldn't be possible. The feature is already there and adding batch uninstall just like there's batch backup should be fine.

Just my opinion of course :) I just like the feature really and it's not too much out of place.

**Comment by ildar** [comment]
My 5 cents.
1. I hardly can imagine a usecase for batch uninstall
2. I'd restrict oab to uninstall only those apps that were backed up

> --
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by Akianonymus** [comment]
Closing this pr for now (maybe forever)

**Pull request closed without merging**
