### PR TITLE
Fixed typographical error, changed aggresive to aggressive in README.

### PR DESCRIPTION
**Pull request by orthographic-pedant**
@jensstein, I've corrected a typographical error in the documentation of the [oandbackup](https://github.com/jensstein/oandbackup) project. You should be able to merge this pull request automatically. However, if this was intentional or if you enjoy living in linguistic squalor, please let me know and [create an issue](https://github.com/thoppe/orthographic-pedant/issues/new) on my home repository.

### CODE REVIEW

**Comment by jensstein** [comment]
i'm sorry, i think i'd rather not receive pull requests from bots as spammy as this one. please go back to reddit or where you came from.
also, i wouldn't necessarily agree with your opinion that a spelling error is linguistic squalor. this project also welcomes people who might not be perfectly fluent in english.

**Comment by thoppe** [comment]
At your request, I've added your user profile to the blacklist. You will hear nothing else from the @orthographic-pedant. Out of curiosity, why do you think this bot is from Reddit?

**Comment by jensstein** [comment]
thanks. i don't actually think the bot is from reddit. it's just that the tendency to use spammy bots to correct others (and just feeling the need to correct others in general) is so prevalent there and this bot reminded me of it.
imagine what this place would be like if in addition to spelling bots there were bots that corrected letter case, bots that corrected grammar, bots that made stylistic recommendations, parody bots that made smileys or unflipped flipped tables or whatever.

**Comment by orthographic-pedant** [comment]
Respectfully, I think that the overall effect would be positive. To use the
Reddit analogy, in addition to the spam bots, there are bots that provide
context (like wikipedia links) bots that aggregate (like link collectors)
and bots that are a service (bitcoin tips and remind me).

The beauty of a github bot IMHO is that it is invisible to the end user. If
the bots are positive then they are only improving your otherwise already
great project.

Does the bot have to be snarky? No. That one is on me. The feedback ratio
is about 50%, 45% loves it and 5% strongly dislike it.

**Pull request closed without merging**
