### PR TITLE
Allow batch uninstallation

### PR DESCRIPTION
**Pull request by Lonami**
Nice project, but I was missing this feature. The style of the project is not something I particularly like so I plan on working on my own fork from now on. Maybe convert it to Kotlin. However, I still wanted to make this pull request in case anyone else finds it useful :)

### CODE REVIEW

**Comment by Lonami** [comment]
By the way, I added a lot of commits before I realized batch uninstallation was much easier. Initially I planned on long click to enable multiple select. You may want to just squash them.

**Comment by ildar** [comment]
@Lonami, it's so great you want to take over this great project. Keep up! 👍

**Comment by Lonami** [comment]
This project indeed supports super old Android versions. I may pump up the minimum version to something like 4.x.

**Comment by nicoursi** [comment]
I wonder why this hasn't been merged already

**Pull request closed without merging**
